# Generated by Django 4.1.6 on 2023-02-06 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Saldo')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100, verbose_name='Senha')),
                ('picture', models.ImageField(upload_to='uploads', verbose_name='Imagem')),
                ('age', models.IntegerField(verbose_name='Idade')),
                ('rate', models.IntegerField(blank=True, null=True, verbose_name='Avaliação')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('color', models.CharField(max_length=100, verbose_name='Cor')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('picture', models.ImageField(upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='MotoTaxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100, verbose_name='Senha')),
                ('picture', models.ImageField(upload_to='uploads', verbose_name='Imagem')),
                ('age', models.IntegerField(verbose_name='Idade')),
                ('rate', models.IntegerField(blank=True, null=True, verbose_name='Avaliação')),
                ('cnh', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('balance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.balance', verbose_name='Saldo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Valor')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Distância')),
                ('payment', models.CharField(max_length=100, verbose_name='Pagamento')),
                ('cli', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='users.client', verbose_name='Cliente')),
                ('moto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='users.mototaxi', verbose_name='Moto Taxi')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo')),
                ('text', models.TextField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Nota')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.client', verbose_name='Cliente')),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mototaxi', verbose_name='Perfil')),
            ],
        ),
        migrations.AddField(
            model_name='mototaxi',
            name='history',
            field=models.ManyToManyField(blank=True, to='users.ride', verbose_name='Historico'),
        ),
        migrations.AddField(
            model_name='mototaxi',
            name='motorcycle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.motorcycle', verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='client',
            name='Favorite',
            field=models.ManyToManyField(blank=True, to='users.mototaxi', verbose_name='Favoritos'),
        ),
        migrations.AddField(
            model_name='client',
            name='balance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.balance', verbose_name='Saldo'),
        ),
        migrations.AddField(
            model_name='client',
            name='history',
            field=models.ManyToManyField(blank=True, to='users.ride', verbose_name='Historico'),
        ),
    ]
