# Generated by Django 4.1.6 on 2023-02-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_cli_ride_clinte_rename_moto_ride_mototax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='owner',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
