# Generated by Django 4.1.6 on 2023-02-06 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_ride_clinte_alter_ride_mototax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='owner',
        ),
    ]
